[package]
name = "arush-seed"
version = "0.1.0"
authors = ["Yu Jing <yu@argcv.com>"]


#[dependencies.arush]
#git = "https://github.com/yuikns/arush"

[dependencies]
#[dependencies]
#arush = { git = "https://github.com/yuikns/arush.git", rev = "36896614" }
rand="0.3.0"
arush="0.0.1"

