[package]
name = "arush-seed"
version = "0.1.0"
authors = ["Yu Jing <yu@argcv.com>"]


#[dependencies.r]
#git = "https://github.com/yuikns/r"

[dependencies]
#r = {path="../r"}
r = { git = "https://github.com/yuikns/r.git", rev = "0dc4ef" }
#rand="0.3.0"
# r="0.0.1"

